---
title: "Publicações"
description: 
  Este espaço será destinado para as principais publicações desenvolvidas durante minha trajetoria acadêmica. 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{=html}
<style>
body {
text-align: justify}
</style>
```
## Artigos Publicados

### 2025
[GOULART, I. C. G. R. ; BRASILEIRO, B.P. ; SANTIN, D. ; **AZEREDO, A. A. C.** . Determinantes da adoção de tecnologias por produtores de erva-mate no Brasil. CADERNO PEDAGÓGICO (LAJEADO. ONLINE), v. 22, p. 1-21, 2025.](https://ojs.studiespublicacoes.com.br/ojs/index.php/cadped/article/view/14127){target="_blank"}

### 2024
[CORTEZ, J. W. M.; DOLINSKI, M. A.; MEDINA, C. V.; **DE AZEREDO, A. A. C.**; ZANETTE, F. Arbuscular mycorrhizal fungi and phosphorus affect Araucaria angustifolia seedling growth. Ciencia e investigación agraria: revista latinoamericana de ciencias de la agricultura, 51(1), 44-56.](https://dialnet.unirioja.es/servlet/articulo?codigo=9499285){target="_blank"}

### 2023

-   [VILCATOMA-MEDINA, C.; DOLINSKI, M.A.; MEDOZA-CORTEZ, J.W.; **AZEREDO, A.A.C.**; BIASI, L.A. ; TOFANELLI, M.B.D. **Mycorrhizal fungi and phosphate fertilization in the formation of seedlings of vine rootstock -IAC-766 Campinas**. REVISTA CHAPINGO. SERIE: HORTICULTURA, v. 29, p. 33-46, 2023.](https://revistas.chapingo.mx/horticultura/?section=articles&subsec=issues&numero=306&articulo=2810){target="_blank"}

-   [HATER, A. ; ANTUNES, W.R. ; AZEREDO, A.A.C. ; SILVA, S.D.A.E. ; OLIVEIRA, R.A. **Early screening for cold tolerance in sugarcane breeding**. PESQUISA AGROPECUÁRIA BRASILEIRA (ONLINE), v. 58, p. 1-11, 2023.](hhttps://www.scielo.br/j/pab/a/dJywmbW3qnXszV8VhxLQcMh/?lang=en){target="_blank"}

### 2022

-   [BORELLA, JULIANE ; BRASILEIRO, B.P. ; **DE AZEREDO, A.A.C.** ; RUARO, LUCIMERIS ; DE OLIVEIRA, R.A. ; BESPALHOK FILHO, JOÃO CARLOS. **Resistance to orange rust associated with the G1 molecular marker in parents of Brazilian RB sugarcane varieties**. GENETICS AND MOLECULAR RESEARCH. v. 21, p. 1-12, 2022](https://www.geneticsmr.com/articles/resistance-orange-rust-associated-g1-molecular-marker-parents-brazilian-rb-sugarcane){target="_blank"}

### 2021

-   [BORELLA, JULIANE ; PORTELA BRASILEIRO, BRUNO ; **DE AZEREDO, AMARO AFONSO CAMPOS**; RUARO, LUCIMERIS ; DE OLIVEIRA, RICARDO AUGUSTO ; BESPALHOK FILHO, JOÃO CARLOS . **Reaction to Brown Rust and Presence of the Bru1 Gene in Brazil/RIDESA Sugarcane Parents**. SUGAR TECH, v. 23, p. 1-8, 2021.](https://link.springer.com/article/10.1007%2Fs12355-021-00992-6){target="_blank"}

### 2020

-   [VERISSIMO, MARIO ALVARO ALOISIO; **AZEREDO, AMARO AFONSO CAMPOS DE** ; SILVA, SERGIO DELMAR DOS ANJOS E ; BRASILEIRO, BRUNO PORTELA ; BESPALHOK FILHO, JOÃO CARLOS ; DAROS, EDELCLAITON ; OLIVEIRA, RICARDO AUGUSTO DE. **Selection of sugarcane families and clones under cold stress**. CIENCIA RURAL, v. 50, p. 1-13, 2020.](https://www.scielo.br/j/cr/a/SBKPFCfh434FRFMYsn84Dtc/?lang=en){target="_blank"}

-   [**DE AZEREDO, AMARO AFONSO CAMPOS**; BHERING, LEONARDO LOPES; DE OLIVEIRA, RICARDO AUGUSTO ; CRUZ, COSME DAMIÃO ; BESPALHOK FILHO, JOÃO CARLOS; BRASILEIRO, BRUNO PORTELA. **Fuzzy controller in the selection of sugarcane and energy cane ideotypes**. EUPHYTICA (DORDRECHT. ONLINE), v. 216, p. 1-15, 2020.](https://link.springer.com/article/10.1007%2Fs10681-020-02626-6){target="_blank"}

-   [JUNIOR, A.R. ; **de AZEREDO, A.A.C.**; ROMANO, T.; BRASILEIRO, B.P.; BESPALHOK FILHO, J.C.; RUARO, LUCIMERIS; DAROS, E.; Oliveira, R.A. **Energy-cane: resistant to major sugarcane diseases?**. Idesia (Arica), v. 38, p. 17, 2020.](https://www.scielo.cl/pdf/idesia/v38n4/0718-3429-idesia-38-04-17.pdf){target="_blank"}

### 2017

-   [**de AZEREDO, A. A. C.**; BHERING, L.L.; BRASILEIRO, B.P.; CRUZ, C.D.; SILVEIRA, L. C. I.; Oliveira, R.A.; BESPALHOK FILHO, J. C.; DAROS, E. **Comparison between different selection indices in energy cane breeding**. Genetics and Molecular Research, v. 16, p. 1-12, 2017.](http://www.funpecrp.com.br/gmr/year2017/vol16-1/pdf/gmr-16-01-gmr.16019535.pdf){target="_blank"}

-   [JÚNIOR, A.R. FERNANDES; **DE AZEREDO, A.A.C.**; DE OLIVEIRA, R.A.; FILHO, J.C. BESPALHOK; IDO, O.T.; DAROS, E.; BRASILEIRO, B.P.**Agricultural performance and genetic parameters for yield-related traits of sugar- and energy cane families derived from planned crosses**. GENETICS AND MOLECULAR RESEARCH, v. 16, p. 1-11, 2017.](http://www.funpecrp.com.br/gmr/year2017/vol16-3/pdf/gmr-16-03-gmr.16039773.pdf)

### 2016

-   [**DE AZEREDO, A.A.C.**; BHERING, L.L.; BRASILEIRO, B.P.; CRUZ, C.D.; BARBOSA, M.H.P. **Selection in sugarcane based on inbreeding depression**. Genetics and Molecular Research, v. 15, p. 1-11, 2016.](http://www.funpecrp.com.br/gmr/year2016/vol15-2/pdf/gmr7965.pdf){target="_blank"}

## Divulgação científica

-  [Gráfico animado mostra áreas canavieiras desde 1980
Trabalho é de Afonso Campos de Azeredo](https://jornalcana.com.br/grafico-animado-mostra-areas-canavieiras-desde-1980){target="_blank"}
-   [Blog Genética Agronômica](https://geneticaagronomica.blogspot.com/){target="_blank"}

## Livros

-   [**50 Anos de Variedades RB de Cana-de-Açúcar 30 Anos de RIDESA**](https://www.ridesaufpr.com/_files/ugd/204f2b_8477bd948c7e4955a42e1f25d1ea49ac.pdf){target="_blank"} 
-   [**50 Years of RB Sugarcane Varieties 30 Years RIDESA**](https://www.ridesaufpr.com/_files/ugd/204f2b_8477bd948c7e4955a42e1f25d1ea49ac.pdf){target="_blank"}
